apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app-deployment
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
        - name: html-app-container
          image: prayags/html-app2:latest  # Use your Docker image
          ports:
            - containerPort: 80
      imagePullSecrets:  # Specify the secret for image pull
        - name: dockerhub-secret  # Reference the secret you created

---
apiVersion: v1
kind: Service
metadata:
  name: html-app-service
spec:
  selector:
    app: html-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Adjust the service type as needed
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: html-app-ingress
spec:
  rules:
    - host: web.ingress.com  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: html-app-service
                port:
                  number: 80
