apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: CnsKICAiYXV0aHMiOiB7CiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8iOiB7CiAgICAgICJhY2Nlc3NfdG9rZW4iOiAiZGNrcl9wYXRfUXpVbGJWS1RBRUNzcU9LM0x3UFowY2VBTzk4IgogICAgfQogIH0KfQo=
