apiVersion: v1
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImNISmhlV0ZuY3pwemREUXlNakl6TUMwMSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
